name: CD

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

concurrency:
  group: cd
  cancel-in-progress: true

env:
    NODE_VERSION: 24

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Configure Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
        env:
          BASE_PATH: ${{ steps.pages.outputs.base_path }}

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: dist

  deploy-github-pages:
    name: Deploy to GitHub Pages
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - id: deployment
        uses: actions/deploy-pages@v5

